### ISSUE TITLE
[Enhancement]: Linux Via AppImage

### ISSUE THREAD

**Issue by arran4** [wgh136/PicaComic#546]
### 描述/Description

Can you please use something like:
https://appimage-builder.readthedocs.io/en/latest/examples/flutter.html

To build an AppImage version for Linux?

The action will probably look a little like this:
```
name: Build Linux
run-name: Build Linux
on:
  workflow_dispatch: {}
jobs:
  Build_Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev lld clang
    - run: flutter pub get
    - run: flutter build linux --release
    - name: Install appimagetool
      run: |
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
    - name: Create AppImage
      run: |
        mkdir -p AppDir/usr/bin
        cp -r build/linux/x64/release/bundle/* AppDir/usr/bin/
        cp AppDir/usr/bin/data/flutter_assets/assets/app.desktop AppDir/
        cp AppDir/usr/bin/data/flutter_assets/assets/app.png AppDir/
        ./appimagetool-x86_64.AppImage AppDir
        mv PicaComic*.AppImage PicaComic.AppImage
    - uses: actions/upload-artifact@v4
      with:
        name: PicaComic.AppImage
        path: PicaComic.AppImage
```

### 操作系统/Operating System

other
